### ISSUE TITLE
Does DT/BDT select the optimal branch bit by the Gini index criterion or the gain?

### ISSUE THREAD

**Issue by dairui777** [xgr19/Mousika#1]
Hello, author.
In `tree.py(line 116)` and `SoftTree.py(line 115)`, `gain = current_gini - next_gini` is calculated. Does DT/BDT  select the optimal branch bit by the Gini index criterion or the gain?
Thanks a lot!

**Comment by ljy2222** [comment]
> Hello, author. In `tree.py(line 116)` and `SoftTree.py(line 115)`, `gain = current_gini - next_gini` is calculated. Does DT/BDT select the optimal branch bit by the Gini index criterion or the gain? Thanks a lot!

Thanks for your question. Our implementation of DT/BDT uses the same criterion as sklearn (https://scikit-learn.org/stable/modules/generated/sklearn.tree.DecisionTreeClassifier.html). For the optimal branch, we choose the direction that leads to the fastest decrease in Gini.

**Comment by dairui777** [comment]
Got it, thanks!
